 CREATE TABLE [dbo].[_TABLENAME_](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Culture] [nvarchar](32) NULL,
	[Name] [nvarchar](64) NULL,
	[Value] [nvarchar](max) NULL,
 CONSTRAINT [PK__TABLENAME_] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [_TABLENAME__Idx] ON [dbo].[_TABLENAME_]
(
	[Culture] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO